[TECH-6504] fixed `UIRequiredDeviceCapabilities` value to `arm64`
Fixes this error during Apple deployment:

> Error: Asset validation failed This bundle is invalid. The key
UIRequiredDeviceCapabilities contains value 'armv64' which is
incompatible with the MinimumOSVersion value of '15.1'.