[TECH-6504] fixed error with secure token storage
Fixed this error:
> Error storing data [TypeError: _reactNativeSensitiveInfo.default.setItem is not a function (it is undefined)]

which caused storing and retrieving secure data (the auth token and the
fcm token) to fail.

This error is due to the `react-native-sensitive-info` library (which is used by
the `redux-persist-sensitive-storage` library) using an outdated method for
importing native code:
https://github.com/mCodex/react-native-sensitive-info/issues/424#issuecomment-2500764917

Fixed by applying a patch via `yarn patch` (https://yarnpkg.com/cli/patch) that
changes how the native methods are merged into the js module export:
https://github.com/mCodex/react-native-sensitive-info/issues/424#issuecomment-2511187606