[TECH-6504] fixed jest tests failing due to enzyme error
Jest tests were failing due to the following error:
> Cannot find module 'cheerio/lib/utils' from 'node_modules/enzyme/build/Utils.js'

Enzyme is using an old import path for cheerio (though it's not clear why that
path has changed, given that enzyme pegged the cheerio dependency to fix this
issue: https://github.com/enzymejs/enzyme/issues/2558).

Fixed by patching in code to replace the bad import.

Also updated to `enzyme-adapter-react-18`.